services:
  postgres:
    image: docker.io/postgres:16-alpine
    container_name: fault-postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    env_file: ../../.env
    #domain owner keeps this env
volumes:
  pgdata:
