
services:
  openobserve:
    container_name: openobserve
    image: public.ecr.aws/zinclabs/openobserve:latest
    ports:
      - "5080:5080" 
    volumes:
      - oodata:/data:Z
    env_file:
      - ../../.env

volumes:
  oodata:
